// Generate PowerPoint presentation from demo data
// Usage: node generate-pptx.mjs
import PptxGenJS from 'pptxgenjs'

const BASE = 'http://localhost:3004'
let TOKEN = ''

async function login() {
  const r = await fetch(`${BASE}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'superadmin@local', password: 'Super1!admin' }),
  })
  const d = await r.json()
  TOKEN = d.token
}

async function get(path) {
  const r = await fetch(`${BASE}${path}`, {
    headers: { Authorization: `Bearer ${TOKEN}`, 'X-Project-Id': '1' },
  })
  return r.json()
}

await login()

// Fetch all data
const [dashboard, items, labor, risks, issues, changes, assumptions, tasks, testsets] = await Promise.all([
  get('/api/dashboard'),
  get('/api/items?'),
  get('/api/labor'),
  get('/api/risks'),
  get('/api/issues'),
  get('/api/changes'),
  get('/api/assumptions'),
  get('/api/tasks'),
  get('/api/testsets'),
])

// ── Helpers ──────────────────────────────────────────────────────
const fmt = (n) => n == null ? '–' : new Intl.NumberFormat('cs-CZ').format(Math.round(n))
const fmtK = (n) => n == null ? '–' : (n >= 1000000 ? `${(n/1000000).toFixed(1)}M` : n >= 1000 ? `${Math.round(n/1000)}K` : String(Math.round(n)))
const pct = (n) => n == null ? '–' : `${n}%`
const S = dashboard.summary

// ── Theme colors ─────────────────────────────────────────────────
const C = {
  dark:    '1a1a2e',
  accent:  'FFCC00',   // brand yellow
  blue:    '3b82f6',
  green:   '22c55e',
  red:     'ef4444',
  orange:  'f97316',
  gray:    '6b7280',
  grayL:   'f3f4f6',
  white:   'FFFFFF',
  black:   '111827',
}

const pptx = new PptxGenJS()
pptx.layout = 'LAYOUT_WIDE' // 13.33 x 7.5
pptx.author = 'PM Tool'
pptx.subject = 'Warehouse Modernization Project'
pptx.title = 'Warehouse Modernization — Project Status Report'

// ── Master slide definition ──────────────────────────────────────
function addHeader(slide, title, subtitle) {
  // Top bar
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.8, fill: { color: C.dark } })
  slide.addText(title, { x: 0.5, y: 0.12, w: 10, h: 0.55, color: C.accent, fontSize: 24, bold: true, fontFace: 'Segoe UI' })
  if (subtitle) {
    slide.addText(subtitle, { x: 0.5, y: 0.48, w: 10, h: 0.3, color: C.white, fontSize: 11, fontFace: 'Segoe UI' })
  }
  // Bottom accent line
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 7.35, w: '100%', h: 0.15, fill: { color: C.accent } })
  slide.addText('PM Tool — Confidential', { x: 0.5, y: 7.08, w: 5, h: 0.25, color: C.gray, fontSize: 8, fontFace: 'Segoe UI' })
}

function kpiBox(slide, x, y, w, h, label, value, color = C.blue) {
  slide.addShape(pptx.ShapeType.rect, { x, y, w, h, fill: { color: C.white }, shadow: { type: 'outer', blur: 4, offset: 2, color: '000000', opacity: 0.15 }, rectRadius: 0.08 })
  slide.addText(value, { x, y: y + 0.08, w, h: h * 0.55, align: 'center', color, fontSize: 22, bold: true, fontFace: 'Segoe UI' })
  slide.addText(label, { x, y: y + h * 0.55, w, h: h * 0.4, align: 'center', color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 1: Title
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: '100%', fill: { color: C.dark } })
  // Yellow accent block
  s.addShape(pptx.ShapeType.rect, { x: 0, y: 2.8, w: '100%', h: 2.0, fill: { color: C.accent } })
  s.addText('Warehouse Modernization\nProject Status Report', { x: 1, y: 2.9, w: 11, h: 1.6, color: C.dark, fontSize: 36, bold: true, fontFace: 'Segoe UI', lineSpacingMultiple: 1.1 })
  s.addText('Hlavní projekt  •  March 2026', { x: 1, y: 5.1, w: 11, h: 0.5, color: C.white, fontSize: 16, fontFace: 'Segoe UI' })
  s.addText('Generated by PM Tool', { x: 1, y: 6.5, w: 11, h: 0.4, color: '888888', fontSize: 11, fontFace: 'Segoe UI' })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 2: Executive Summary
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Executive Summary', 'High-level project KPIs')

  // Row 1: Financial KPIs
  const y1 = 1.1
  kpiBox(s, 0.4, y1, 2.0, 1.05, 'Total Budget', `${fmtK(S.grandTotal)} CZK`, C.blue)
  kpiBox(s, 2.6, y1, 2.0, 1.05, 'Material Budget', `${fmtK(S.totalEstimated)} CZK`, C.blue)
  kpiBox(s, 4.8, y1, 2.0, 1.05, 'Actual Spent', `${fmtK(S.totalActual)} CZK`, C.green)
  kpiBox(s, 7.0, y1, 2.0, 1.05, 'Remaining', `${fmtK(S.remaining)} CZK`, C.orange)
  kpiBox(s, 9.2, y1, 2.0, 1.05, 'CAPEX Total', `${fmtK(S.totalCapex)} CZK`, C.dark)
  kpiBox(s, 11.4, y1, 1.5, 1.05, 'Spent %', pct(S.spentPct), S.spentPct > 80 ? C.red : C.blue)

  // Row 2: Labor
  const y2 = 2.4
  kpiBox(s, 0.4, y2, 2.0, 1.05, 'Labor Budget', `${fmtK(S.totalLabor)} CZK`, C.blue)
  kpiBox(s, 2.6, y2, 2.0, 1.05, 'Labor Spent', `${fmtK(S.totalLaborSpent)} CZK`, C.green)
  kpiBox(s, 4.8, y2, 2.0, 1.05, 'Budget Items', String(S.totalItems), C.dark)
  kpiBox(s, 7.0, y2, 2.0, 1.05, 'Total Risks', String(S.totalRisks), S.totalRisks > 5 ? C.orange : C.blue)
  kpiBox(s, 9.2, y2, 2.0, 1.05, 'Open Issues', String(S.highSeverityIssues), S.highSeverityIssues > 0 ? C.red : C.green)
  kpiBox(s, 11.4, y2, 1.5, 1.05, 'Pending CRs', String(S.pendingChangeRequests), C.orange)

  // Row 3: Project Plan
  const y3 = 3.7
  kpiBox(s, 0.4, y3, 2.0, 1.05, 'Plan Progress', pct(S.ppProgressPct), C.blue)
  kpiBox(s, 2.6, y3, 2.0, 1.05, 'Tasks Done', `${S.ppDoneTasks} / ${S.ppTotalTasks}`, C.green)
  kpiBox(s, 4.8, y3, 2.0, 1.05, 'Overdue Tasks', String(S.ppOverdueTasks), S.ppOverdueTasks > 0 ? C.red : C.green)
  kpiBox(s, 7.0, y3, 2.0, 1.05, 'Critical Path', String(S.ppCriticalTasks), C.red)
  kpiBox(s, 9.2, y3, 2.0, 1.05, 'Schedule Var.', S.ppScheduleVarianceDays != null ? `${S.ppScheduleVarianceDays > 0 ? '+' : ''}${S.ppScheduleVarianceDays}d` : '–', S.ppScheduleVarianceDays > 0 ? C.red : C.green)
  const healthColor = S.ppHealthStatus === 'critical' ? C.red : S.ppHealthStatus === 'at_risk' ? C.orange : C.green
  const healthLabel = S.ppHealthStatus === 'critical' ? 'CRITICAL' : S.ppHealthStatus === 'at_risk' ? 'AT RISK' : 'ON TRACK'
  kpiBox(s, 11.4, y3, 1.5, 1.05, 'Health', healthLabel, healthColor)

  // Status distribution — horizontal bar
  const y4 = 5.1
  s.addText('Budget Item Status Distribution', { x: 0.4, y: y4, w: 6, h: 0.35, color: C.black, fontSize: 12, bold: true, fontFace: 'Segoe UI' })
  const statusColors = { 'Complete': C.green, 'Implementation': C.blue, 'Tender Closed': '8b5cf6', 'Tender Planned': C.orange, 'Not Tender Needed': C.gray, 'Unset': 'cbd5e1' }
  const total = Object.values(S.byStatus).reduce((a, b) => a + b, 0)
  let barX = 0.4
  const barW = 12.5
  const barY = y4 + 0.4
  for (const [status, count] of Object.entries(S.byStatus)) {
    const w = (count / total) * barW
    if (w > 0.01) {
      s.addShape(pptx.ShapeType.rect, { x: barX, y: barY, w, h: 0.35, fill: { color: statusColors[status] || C.gray } })
      if (w > 0.6) {
        s.addText(`${status} (${count})`, { x: barX, y: barY, w, h: 0.35, align: 'center', color: C.white, fontSize: 8, fontFace: 'Segoe UI' })
      }
      barX += w
    }
  }

  // Approval distribution
  const y5 = 6.1
  s.addText('Approval Status', { x: 0.4, y: y5, w: 6, h: 0.35, color: C.black, fontSize: 12, bold: true, fontFace: 'Segoe UI' })
  const approvalColors = { 'Approved': C.green, 'Pending': C.orange, 'Not Required': C.gray }
  const totalApproval = Object.values(S.byApproval).reduce((a, b) => a + b, 0)
  let aBarX = 0.4
  for (const [status, count] of Object.entries(S.byApproval)) {
    const w = (count / totalApproval) * barW
    if (w > 0.01) {
      s.addShape(pptx.ShapeType.rect, { x: aBarX, y: y5 + 0.4, w, h: 0.35, fill: { color: approvalColors[status] || C.gray } })
      if (w > 0.6) {
        s.addText(`${status} (${count})`, { x: aBarX, y: y5 + 0.4, w, h: 0.35, align: 'center', color: C.white, fontSize: 8, fontFace: 'Segoe UI' })
      }
      aBarX += w
    }
  }
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 3: Budget by Category
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Budget by Category', 'Estimated vs Actual costs per category')

  const cats = dashboard.byCategory
  const maxEst = Math.max(...cats.map(c => c.estimated))

  const startY = 1.2
  const barMaxW = 7.5
  const labelW = 3.5
  const rowH = 0.7

  cats.forEach((cat, i) => {
    const y = startY + i * rowH
    // Category name
    s.addText(cat.category, { x: 0.4, y, w: labelW, h: 0.3, color: C.black, fontSize: 11, bold: true, fontFace: 'Segoe UI' })
    s.addText(`${fmt(cat.estimated)} CZK est.  •  ${fmt(cat.actual)} CZK act.  •  ${cat.count} items`, { x: 0.4, y: y + 0.28, w: labelW, h: 0.25, color: C.gray, fontSize: 8, fontFace: 'Segoe UI' })

    // Estimated bar
    const estW = Math.max(0.05, (cat.estimated / maxEst) * barMaxW)
    s.addShape(pptx.ShapeType.rect, { x: labelW + 0.3, y, w: estW, h: 0.28, fill: { color: C.blue }, rectRadius: 0.04 })
    if (estW > 0.8) s.addText(fmtK(cat.estimated), { x: labelW + 0.3, y, w: estW, h: 0.28, align: 'center', color: C.white, fontSize: 8, fontFace: 'Segoe UI' })

    // Actual bar
    if (cat.actual > 0) {
      const actW = Math.max(0.05, (cat.actual / maxEst) * barMaxW)
      s.addShape(pptx.ShapeType.rect, { x: labelW + 0.3, y: y + 0.32, w: actW, h: 0.22, fill: { color: C.green }, rectRadius: 0.04 })
      if (actW > 0.8) s.addText(fmtK(cat.actual), { x: labelW + 0.3, y: y + 0.32, w: actW, h: 0.22, align: 'center', color: C.white, fontSize: 8, fontFace: 'Segoe UI' })
    }
  })

  // Legend
  const legY = startY + cats.length * rowH + 0.3
  s.addShape(pptx.ShapeType.rect, { x: labelW + 0.3, y: legY, w: 0.3, h: 0.2, fill: { color: C.blue } })
  s.addText('Estimated', { x: labelW + 0.7, y: legY, w: 1.5, h: 0.2, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
  s.addShape(pptx.ShapeType.rect, { x: labelW + 2.3, y: legY, w: 0.3, h: 0.2, fill: { color: C.green } })
  s.addText('Actual', { x: labelW + 2.7, y: legY, w: 1.5, h: 0.2, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 4: Top Budget Items
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Top Budget Items', 'Largest items by estimated cost')

  const sorted = [...items].sort((a, b) => (b.totalEstCost || 0) - (a.totalEstCost || 0)).slice(0, 12)

  const rows = [
    [
      { text: '#', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Description', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Category', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Est. Cost', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Actual', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Approval', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
    ]
  ]

  sorted.forEach((item, i) => {
    const bg = i % 2 === 0 ? C.white : C.grayL
    rows.push([
      { text: String(i + 1), options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: item.description || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: item.category || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: `${fmt(item.totalEstCost)}`, options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: item.actualPrice ? fmt(item.actualPrice) : '–', options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: item.tenderStatus || '–', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: item.approval || '–', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
    ])
  })

  s.addTable(rows, {
    x: 0.3, y: 1.1, w: 12.7,
    colW: [0.4, 3.8, 1.8, 1.5, 1.5, 1.6, 1.2],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.38,
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 5: Labor Costs
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Labor Costs', `Total: ${fmtK(S.totalLabor)} CZK  •  Spent: ${fmtK(S.totalLaborSpent)} CZK`)

  const rows = [
    [
      { text: 'Role', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Person', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Department', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'MD Rate', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'MDs', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Budget', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Spent', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: '% Used', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
    ]
  ]

  for (const [i, lc] of labor.entries()) {
    const budget = (lc.mdRate || 0) * (lc.mdDays || 0)
    const spent = lc.spent || 0
    const usedPct = budget > 0 ? Math.round(spent / budget * 100) : 0
    const bg = i % 2 === 0 ? C.white : C.grayL
    rows.push([
      { text: lc.role || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: lc.personName || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: lc.department || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: fmt(lc.mdRate), options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: String(lc.mdDays || 0), options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: fmt(budget), options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: fmt(spent), options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: `${usedPct}%`, options: { fontSize: 8, align: 'center', color: usedPct > 80 ? C.red : usedPct > 50 ? C.orange : C.green, bold: true, fill: { color: bg } } },
    ])
  }

  s.addTable(rows, {
    x: 0.3, y: 1.1, w: 12.7,
    colW: [2.2, 1.8, 1.3, 1.2, 0.8, 1.6, 1.6, 1.0],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.42,
  })

  // Labor by department chart (horizontal bars)
  const depts = dashboard.laborByDept.sort((a, b) => b.total - a.total)
  const maxDept = Math.max(...depts.map(d => d.total))
  const deptY = 1.1 + (labor.length + 1) * 0.42 + 0.5
  s.addText('Labor by Department', { x: 0.3, y: deptY, w: 5, h: 0.35, color: C.black, fontSize: 12, bold: true, fontFace: 'Segoe UI' })

  depts.forEach((d, i) => {
    const y = deptY + 0.45 + i * 0.45
    s.addText(d.dept, { x: 0.3, y, w: 2, h: 0.35, color: C.black, fontSize: 9, fontFace: 'Segoe UI' })
    const w = Math.max(0.1, (d.total / maxDept) * 6)
    s.addShape(pptx.ShapeType.rect, { x: 2.5, y: y + 0.05, w, h: 0.25, fill: { color: C.blue }, rectRadius: 0.04 })
    s.addText(`${fmtK(d.total)} CZK`, { x: 2.5 + w + 0.15, y, w: 2, h: 0.35, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 6: Risk Management
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Risk Management', `${risks.length} risks identified  •  Exposure score: ${S.riskExposure}`)

  const rows = [
    [
      { text: 'Risk', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Category', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'P', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'I', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Score', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Owner', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Mitigation', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
    ]
  ]

  const sortedRisks = [...risks].sort((a, b) => b.score - a.score)
  for (const [i, r] of sortedRisks.entries()) {
    const bg = i % 2 === 0 ? C.white : C.grayL
    const scoreColor = r.score >= 15 ? C.red : r.score >= 9 ? C.orange : C.green
    rows.push([
      { text: r.title || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: r.category || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: String(r.probability), options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: String(r.impact), options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: String(r.score), options: { fontSize: 9, align: 'center', bold: true, color: scoreColor, fill: { color: bg } } },
      { text: r.status || '', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: r.owner?.name || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: (r.mitigationPlan || '').substring(0, 60) + (r.mitigationPlan?.length > 60 ? '…' : ''), options: { fontSize: 7, fill: { color: bg } } },
    ])
  }

  s.addTable(rows, {
    x: 0.2, y: 1.1, w: 12.9,
    colW: [2.5, 1.1, 0.5, 0.5, 0.6, 1.0, 1.5, 4.5],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.55,
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 7: Issues & Change Requests
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Issues & Change Requests', `${issues.length} issues  •  ${changes.length} change requests`)

  // Issues table
  s.addText('Open Issues', { x: 0.4, y: 1.0, w: 5, h: 0.35, color: C.black, fontSize: 14, bold: true, fontFace: 'Segoe UI' })

  const issueRows = [
    [
      { text: 'Issue', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Type', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Severity', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Owner', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
    ]
  ]
  for (const [i, iss] of issues.entries()) {
    const bg = i % 2 === 0 ? C.white : C.grayL
    const sevColor = iss.severity === 'Critical' ? C.red : iss.severity === 'High' ? C.orange : C.gray
    issueRows.push([
      { text: iss.title || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: iss.type || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: iss.severity || '', options: { fontSize: 8, align: 'center', color: sevColor, bold: true, fill: { color: bg } } },
      { text: iss.status || '', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: iss.owner?.name || '', options: { fontSize: 8, fill: { color: bg } } },
    ])
  }
  s.addTable(issueRows, {
    x: 0.3, y: 1.4, w: 12.7,
    colW: [4.5, 1.5, 1.2, 1.3, 2.0],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.38,
  })

  // Change Requests table
  const crY = 1.4 + (issues.length + 1) * 0.38 + 0.5
  s.addText('Change Requests', { x: 0.4, y: crY, w: 5, h: 0.35, color: C.black, fontSize: 14, bold: true, fontFace: 'Segoe UI' })

  const crRows = [
    [
      { text: 'Change Request', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Type', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Budget Impact', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Timeline', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
    ]
  ]
  for (const [i, cr] of changes.entries()) {
    const bg = i % 2 === 0 ? C.white : C.grayL
    const impactColor = (cr.budgetImpact || 0) > 0 ? C.red : (cr.budgetImpact || 0) < 0 ? C.green : C.gray
    crRows.push([
      { text: cr.title || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: cr.changeType || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: `${(cr.budgetImpact || 0) > 0 ? '+' : ''}${fmt(cr.budgetImpact)} CZK`, options: { fontSize: 8, align: 'right', color: impactColor, bold: true, fill: { color: bg } } },
      { text: cr.timelineImpact || '–', options: { fontSize: 8, fill: { color: bg } } },
      { text: cr.approvalStatus || '', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
    ])
  }
  s.addTable(crRows, {
    x: 0.3, y: crY + 0.4, w: 12.7,
    colW: [4.5, 1.2, 2.0, 2.5, 1.5],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.38,
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 8: Assumptions
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Assumptions', `${assumptions.length} total  •  ${S.validatedPct}% validated  •  ${S.overdueAssumptions} overdue  •  ${S.expiringSoon} expiring soon`)

  const rows = [
    [
      { text: 'Assumption', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Category', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
      { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Validation Date', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Budget Impact', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'right' } },
      { text: 'Exposure', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
      { text: 'Owner', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
    ]
  ]

  const sortedAssumptions = [...assumptions].sort((a, b) => (b.exposureScore || 0) - (a.exposureScore || 0))
  for (const [i, a] of sortedAssumptions.entries()) {
    const bg = i % 2 === 0 ? C.white : C.grayL
    const statusColor = a.status === 'Validated' || a.status === 'Closed' ? C.green : a.status === 'Under review' ? C.orange : C.blue
    rows.push([
      { text: a.title || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: a.category || '', options: { fontSize: 8, fill: { color: bg } } },
      { text: a.status || '', options: { fontSize: 8, align: 'center', color: statusColor, bold: true, fill: { color: bg } } },
      { text: a.validationDate ? new Date(a.validationDate).toLocaleDateString('cs-CZ') : '–', options: { fontSize: 8, align: 'center', fill: { color: bg } } },
      { text: a.budgetImpact ? `${fmt(a.budgetImpact)} CZK` : '–', options: { fontSize: 8, align: 'right', fill: { color: bg } } },
      { text: String(a.exposureScore || 0), options: { fontSize: 9, align: 'center', bold: true, color: (a.exposureScore || 0) >= 10 ? C.red : (a.exposureScore || 0) >= 5 ? C.orange : C.green, fill: { color: bg } } },
      { text: a.owner?.name || '', options: { fontSize: 8, fill: { color: bg } } },
    ])
  }

  s.addTable(rows, {
    x: 0.2, y: 1.1, w: 12.9,
    colW: [3.5, 1.1, 1.2, 1.3, 1.5, 0.9, 1.8],
    border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
    fontFace: 'Segoe UI',
    rowH: 0.55,
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 9: Project Plan Overview
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Project Plan', `${S.ppTotalTasks} tasks  •  ${pct(S.ppProgressPct)} complete  •  ${S.ppStart?.substring(0, 10) || '–'} → ${S.ppEnd?.substring(0, 10) || '–'}`)

  // Phase summary cards
  const phases = tasks.filter(t => t.type === 'phase').sort((a, b) => a.sortOrder - b.sortOrder)
  const phaseW = 12.5 / Math.max(phases.length, 1)

  phases.forEach((ph, i) => {
    const x = 0.4 + i * (phaseW + 0.1)
    const y = 1.2
    const children = tasks.filter(t => t.parentId === ph.id)
    const allChildren = tasks.filter(t => {
      if (t.parentId === ph.id) return true
      return children.some(c => t.parentId === c.id)
    })
    const phaseTasks = allChildren.filter(t => t.type === 'task')
    const done = phaseTasks.filter(t => t.status === 'done').length
    const total = phaseTasks.length
    const progressPct = ph.progress || 0

    // Card
    const phColor = progressPct >= 90 ? C.green : progressPct >= 50 ? C.blue : progressPct > 0 ? C.orange : C.gray
    s.addShape(pptx.ShapeType.rect, { x, y, w: phaseW - 0.1, h: 2.2, fill: { color: C.white }, shadow: { type: 'outer', blur: 4, offset: 2, color: '000000', opacity: 0.15 }, rectRadius: 0.08 })
    // Phase color stripe
    s.addShape(pptx.ShapeType.rect, { x, y, w: phaseW - 0.1, h: 0.08, fill: { color: phColor }, rectRadius: 0.04 })

    s.addText(ph.name, { x: x + 0.15, y: y + 0.15, w: phaseW - 0.4, h: 0.5, color: C.black, fontSize: 11, bold: true, fontFace: 'Segoe UI', wrap: true })

    // Progress circle (simplified as text)
    s.addText(`${progressPct}%`, { x: x + 0.15, y: y + 0.65, w: phaseW - 0.4, h: 0.55, color: phColor, fontSize: 28, bold: true, fontFace: 'Segoe UI', align: 'center' })

    // Stats
    s.addText(`${done}/${total} tasks done`, { x: x + 0.15, y: y + 1.25, w: phaseW - 0.4, h: 0.25, color: C.gray, fontSize: 9, fontFace: 'Segoe UI', align: 'center' })

    // Date range
    const start = ph.plannedStart ? new Date(ph.plannedStart).toLocaleDateString('cs-CZ', { month: 'short', year: '2-digit' }) : '–'
    const end = ph.plannedEnd ? new Date(ph.plannedEnd).toLocaleDateString('cs-CZ', { month: 'short', year: '2-digit' }) : '–'
    s.addText(`${start} → ${end}`, { x: x + 0.15, y: y + 1.5, w: phaseW - 0.4, h: 0.25, color: C.gray, fontSize: 9, fontFace: 'Segoe UI', align: 'center' })

    // Estimated cost
    s.addText(`${fmtK(ph.estimatedCost)} CZK`, { x: x + 0.15, y: y + 1.8, w: phaseW - 0.4, h: 0.25, color: C.blue, fontSize: 10, bold: true, fontFace: 'Segoe UI', align: 'center' })
  })

  // Timeline bar (simplified Gantt)
  const ganttY = 3.7
  s.addText('Timeline Overview', { x: 0.4, y: ganttY, w: 5, h: 0.35, color: C.black, fontSize: 14, bold: true, fontFace: 'Segoe UI' })

  // Find date range
  const allDates = tasks.filter(t => t.plannedStart && t.plannedEnd)
  if (allDates.length > 0) {
    const minDate = new Date(Math.min(...allDates.map(t => new Date(t.plannedStart).getTime())))
    const maxDate = new Date(Math.max(...allDates.map(t => new Date(t.plannedEnd).getTime())))
    const totalDays = (maxDate - minDate) / 86400000
    const ganttW = 10.0
    const ganttX = 3.0

    // Month labels
    const monthStart = new Date(minDate.getFullYear(), minDate.getMonth(), 1)
    let mDate = new Date(monthStart)
    while (mDate <= maxDate) {
      const dayOffset = (mDate - minDate) / 86400000
      const x = ganttX + (dayOffset / totalDays) * ganttW
      if (x >= ganttX && x < ganttX + ganttW) {
        s.addText(mDate.toLocaleDateString('en-US', { month: 'short', year: '2-digit' }), { x, y: ganttY + 0.35, w: 1, h: 0.25, color: C.gray, fontSize: 7, fontFace: 'Segoe UI' })
        s.addShape(pptx.ShapeType.line, { x, y: ganttY + 0.6, w: 0, h: phases.length * 0.5 + 0.2, line: { color: 'e5e7eb', width: 0.5 } })
      }
      mDate = new Date(mDate.getFullYear(), mDate.getMonth() + 1, 1)
    }

    // Today line
    const today = new Date()
    const todayOffset = (today - minDate) / 86400000
    const todayX = ganttX + (todayOffset / totalDays) * ganttW
    if (todayX >= ganttX && todayX <= ganttX + ganttW) {
      s.addShape(pptx.ShapeType.line, { x: todayX, y: ganttY + 0.55, w: 0, h: phases.length * 0.5 + 0.3, line: { color: C.red, width: 1.5 } })
      s.addText('Today', { x: todayX - 0.3, y: ganttY + 0.35, w: 0.7, h: 0.2, color: C.red, fontSize: 7, fontFace: 'Segoe UI', align: 'center' })
    }

    // Phase bars
    phases.forEach((ph, i) => {
      const y = ganttY + 0.65 + i * 0.5
      s.addText(ph.name.replace('Phase ', 'P').substring(0, 20), { x: 0.4, y, w: 2.5, h: 0.35, color: C.black, fontSize: 9, fontFace: 'Segoe UI' })

      if (ph.plannedStart && ph.plannedEnd) {
        const startOffset = (new Date(ph.plannedStart) - minDate) / 86400000
        const endOffset = (new Date(ph.plannedEnd) - minDate) / 86400000
        const barX = ganttX + (startOffset / totalDays) * ganttW
        const barW = Math.max(0.1, ((endOffset - startOffset) / totalDays) * ganttW)
        const phColor2 = (ph.progress || 0) >= 90 ? C.green : (ph.progress || 0) >= 50 ? C.blue : (ph.progress || 0) > 0 ? C.orange : C.gray

        // Background bar
        s.addShape(pptx.ShapeType.rect, { x: barX, y: y + 0.05, w: barW, h: 0.25, fill: { color: 'e5e7eb' }, rectRadius: 0.04 })
        // Progress fill
        if (ph.progress > 0) {
          const fillW = Math.max(0.05, barW * (ph.progress / 100))
          s.addShape(pptx.ShapeType.rect, { x: barX, y: y + 0.05, w: fillW, h: 0.25, fill: { color: phColor2 }, rectRadius: 0.04 })
        }
        // Label
        if (barW > 0.5) {
          s.addText(`${ph.progress}%`, { x: barX, y: y + 0.05, w: barW, h: 0.25, align: 'center', color: C.white, fontSize: 8, bold: true, fontFace: 'Segoe UI' })
        }
      }
    })
  }

  // Key milestones
  const milestones = tasks.filter(t => t.isMilestone).sort((a, b) => new Date(a.plannedEnd) - new Date(b.plannedEnd))
  const msY = ganttY + 0.65 + phases.length * 0.5 + 0.5
  s.addText('Key Milestones', { x: 0.4, y: msY, w: 5, h: 0.35, color: C.black, fontSize: 12, bold: true, fontFace: 'Segoe UI' })
  milestones.forEach((m, i) => {
    const y = msY + 0.4 + i * 0.3
    const date = m.plannedEnd ? new Date(m.plannedEnd).toLocaleDateString('cs-CZ') : '–'
    const statusIcon = m.status === 'done' ? '✓' : '◆'
    const color = m.status === 'done' ? C.green : m.isCriticalPath ? C.red : C.blue
    s.addText(`${statusIcon}  ${m.name}`, { x: 0.6, y, w: 5, h: 0.25, color, fontSize: 9, fontFace: 'Segoe UI' })
    s.addText(date, { x: 5.5, y, w: 2, h: 0.25, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
    if (m.isCriticalPath) s.addText('CRITICAL', { x: 7.5, y, w: 1.5, h: 0.25, color: C.red, fontSize: 8, bold: true, fontFace: 'Segoe UI' })
  })
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 10: Testing Status
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Testing Status', `${testsets.length} test sets`)

  let currentY = 1.1
  for (const ts of testsets) {
    // Fetch test cases for this set
    const cases = ts.cases || ts.testCases || []

    s.addText(ts.name, { x: 0.4, y: currentY, w: 8, h: 0.35, color: C.black, fontSize: 14, bold: true, fontFace: 'Segoe UI' })
    if (ts.notes) s.addText(ts.notes, { x: 0.4, y: currentY + 0.3, w: 8, h: 0.25, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })

    // Status counts
    const statusCounts = {}
    for (const tc of cases) {
      const st = tc.status || 'Not Started'
      statusCounts[st] = (statusCounts[st] || 0) + 1
    }

    // Summary badges
    let badgeX = 0.4
    const badgeY = currentY + 0.6
    const badgeColors = { PASS: C.green, DEFECT: C.red, WIP: C.orange, 'N/A': C.gray, 'Not Started': 'cbd5e1' }
    for (const [status, count] of Object.entries(statusCounts)) {
      const w = 1.4
      s.addShape(pptx.ShapeType.rect, { x: badgeX, y: badgeY, w, h: 0.35, fill: { color: badgeColors[status] || C.gray }, rectRadius: 0.06 })
      s.addText(`${status}: ${count}`, { x: badgeX, y: badgeY, w, h: 0.35, align: 'center', color: status === 'Not Started' ? C.black : C.white, fontSize: 9, bold: true, fontFace: 'Segoe UI' })
      badgeX += w + 0.15
    }

    // Test case rows
    if (cases.length > 0) {
      const tcRows = [
        [
          { text: 'Test Case', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
          { text: 'Status', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9, align: 'center' } },
          { text: 'Tested By', options: { bold: true, color: C.white, fill: { color: C.dark }, fontSize: 9 } },
        ]
      ]
      for (const [i, tc] of cases.entries()) {
        const bg = i % 2 === 0 ? C.white : C.grayL
        const stColor = tc.status === 'PASS' ? C.green : tc.status === 'DEFECT' ? C.red : tc.status === 'WIP' ? C.orange : C.gray
        tcRows.push([
          { text: tc.name || '', options: { fontSize: 8, fill: { color: bg } } },
          { text: tc.status || 'Not Started', options: { fontSize: 8, align: 'center', color: stColor, bold: true, fill: { color: bg } } },
          { text: tc.testedBy || '–', options: { fontSize: 8, fill: { color: bg } } },
        ])
      }
      s.addTable(tcRows, {
        x: 0.3, y: badgeY + 0.5, w: 12.7,
        colW: [6, 2, 3],
        border: { type: 'solid', pt: 0.5, color: 'e5e7eb' },
        fontFace: 'Segoe UI',
        rowH: 0.32,
      })
      currentY = badgeY + 0.5 + (cases.length + 1) * 0.32 + 0.5
    } else {
      currentY += 1.5
    }
  }
}

// ═══════════════════════════════════════════════════════════════════
// SLIDE 11: Key Takeaways / Next Steps
// ═══════════════════════════════════════════════════════════════════
{
  const s = pptx.addSlide()
  addHeader(s, 'Key Takeaways & Next Steps')

  // Left column: Key Stats
  s.addShape(pptx.ShapeType.rect, { x: 0.4, y: 1.1, w: 6, h: 5.8, fill: { color: C.white }, shadow: { type: 'outer', blur: 4, offset: 2, color: '000000', opacity: 0.1 }, rectRadius: 0.1 })
  s.addText('Key Statistics', { x: 0.7, y: 1.2, w: 5, h: 0.4, color: C.dark, fontSize: 16, bold: true, fontFace: 'Segoe UI' })

  const stats = [
    [`Total Budget (Material + Labor)`, `${fmt(S.grandTotal)} CZK`],
    [`Material Estimated`, `${fmt(S.totalEstimated)} CZK`],
    [`Material Spent`, `${fmt(S.totalActual)} CZK (${pct(S.spentPct)})`],
    [`CAPEX Required`, `${fmt(S.totalCapex)} CZK`],
    [`Labor Budget`, `${fmt(S.totalLabor)} CZK`],
    [`Budget Items`, `${S.totalItems}`],
    [`Risks Identified`, `${S.totalRisks} (exposure: ${S.riskExposure})`],
    [`High-Severity Issues`, `${S.highSeverityIssues}`],
    [`Pending Change Requests`, `${S.pendingChangeRequests}`],
    [`Approved Budget Impact`, `${(S.budgetImpactSummary >= 0 ? '+' : '')}${fmt(S.budgetImpactSummary)} CZK`],
    [`Assumptions`, `${S.totalAssumptions} (${pct(S.validatedPct)} validated)`],
    [`Plan Progress`, `${pct(S.ppProgressPct)}`],
    [`Schedule Variance`, `${S.ppScheduleVarianceDays != null ? (S.ppScheduleVarianceDays > 0 ? '+' : '') + S.ppScheduleVarianceDays + ' days' : '–'}`],
    [`Health Status`, S.ppHealthStatus === 'critical' ? 'CRITICAL' : S.ppHealthStatus === 'at_risk' ? 'AT RISK' : 'ON TRACK'],
  ]

  stats.forEach(([label, val], i) => {
    const y = 1.7 + i * 0.37
    s.addText(label, { x: 0.7, y, w: 3.5, h: 0.3, color: C.gray, fontSize: 9, fontFace: 'Segoe UI' })
    s.addText(val, { x: 4.2, y, w: 2, h: 0.3, color: C.black, fontSize: 9, bold: true, fontFace: 'Segoe UI', align: 'right' })
  })

  // Right column: Action Items
  s.addShape(pptx.ShapeType.rect, { x: 6.8, y: 1.1, w: 6, h: 5.8, fill: { color: C.white }, shadow: { type: 'outer', blur: 4, offset: 2, color: '000000', opacity: 0.1 }, rectRadius: 0.1 })
  s.addText('Action Items', { x: 7.1, y: 1.2, w: 5, h: 0.4, color: C.dark, fontSize: 16, bold: true, fontFace: 'Segoe UI' })

  const actions = [
    { icon: '🔴', text: 'Resolve dock leveler #4 hydraulic leak (Critical)', due: 'Mar 5' },
    { icon: '🔴', text: 'Complete SAP EWM API documentation', due: 'Mar 31' },
    { icon: '🟡', text: 'Fix WiFi dead spots in zone B3', due: 'Mar 15' },
    { icon: '🟡', text: 'Review robot fleet delivery timeline with Locus', due: 'May 1' },
    { icon: '🔵', text: 'Submit electrical transformer order tracking', due: 'Mar 15' },
    { icon: '🔵', text: 'Evaluate CR: +4 AMR robots (1.5M CZK)', due: 'Pending' },
    { icon: '🔵', text: 'Validate floor load capacity for AMR fleet', due: 'Mar 31' },
    { icon: '🔵', text: 'Schedule fire department pre-consultation', due: 'Mar' },
    { icon: '⚪', text: 'Prepare training materials for Phase 4', due: 'Jun 1' },
    { icon: '⚪', text: 'Plan cutover rehearsal', due: 'Sep 1' },
  ]

  actions.forEach((a, i) => {
    const y = 1.7 + i * 0.5
    s.addText(a.icon, { x: 7.1, y, w: 0.4, h: 0.3, fontSize: 11 })
    s.addText(a.text, { x: 7.5, y, w: 4.3, h: 0.4, color: C.black, fontSize: 9, fontFace: 'Segoe UI', wrap: true })
    s.addText(a.due, { x: 11.8, y, w: 0.8, h: 0.3, color: C.gray, fontSize: 8, fontFace: 'Segoe UI', align: 'right' })
  })
}

// ═══════════════════════════════════════════════════════════════════
// Save
// ═══════════════════════════════════════════════════════════════════
const filename = 'Warehouse_Modernization_Status_Report.pptx'
await pptx.writeFile({ fileName: filename })
console.log(`\n✅ Presentation saved: ${filename}`)
console.log(`   11 slides, all data from live API`)
